// Central language aliases mapping & language detection (Single Source of Truth)
export const languageAliases = {
    "assembly": "asm",
    "asm": "asm",
    "s": "asm",
    "bash": "bash",
    "sh": "shell",
    "shell": "shell",
    "bat": "bat",
    "cmd": "bat",
    "c": "c",
    "h": "c",
    "c++": "cpp",
    "cpp": "cpp",
    "cc": "cpp",
    "cxx": "cpp",
    "hpp": "cpp",
    "hh": "cpp",
    "hxx": "cpp",
    "c#": "csharp",
    "csharp": "csharp",
    "cs": "csharp",
    "csx": "csharp",
    "cake": "csharp",
    "css": "css",
    "dart": "dart",
    "dockerfile": "dockerfile",
    "docker": "dockerfile",
    "go": "go",
    "graphql": "graphql",
    "html": "html",
    "htm": "html",
    "xhtml": "html",
    "shtml": "html",
    "mdoc": "html",
    "jsp": "html",
    "asp": "html",
    "aspx": "html",
    "jshtm": "html",
    "ini": "ini",
    "java": "java",
    "jav": "java",
    "javascript": "javascript",
    "js": "javascript",
    "es6": "javascript",
    "jsx": "javascript",
    "mjs": "javascript",
    "cjs": "javascript",
    "json": "json",
    "kotlin": "kotlin",
    "kt": "kotlin",
    "lua": "lua",
    "markdown": "markdown",
    "md": "markdown",
    "mdown": "markdown",
    "mkdn": "markdown",
    "mkd": "markdown",
    "mdwn": "markdown",
    "mdtxt": "markdown",
    "mdtext": "markdown",
    "php": "php",
    "php4": "php",
    "php5": "php",
    "phtml": "php",
    "ctp": "php",
    "powershell": "powershell",
    "ps": "powershell",
    "ps1": "powershell",
    "python": "python",
    "py": "python",
    "rpy": "python",
    "pyw": "python",
    "cpy": "python",
    "gyp": "python",
    "gypi": "python",
    "r": "r",
    "ruby": "ruby",
    "rb": "ruby",
    "rust": "rust",
    "rs": "rust",
    "rlib": "rust",
    "scala": "scala",
    "sql": "sql",
    "swift": "swift",
    "typescript": "typescript",
    "ts": "typescript",
    "tsx": "typescript",
    "cts": "typescript",
    "mts": "typescript",
    "xml": "xml",
    "yaml": "yaml",
    "yml": "yaml"
};

/**
 * Detect language name from filename or path based on aliases
 */
export function detectLanguage(filename, aliases = languageAliases) {
    if (!filename || typeof filename !== 'string') return 'javascript';
    const cleanName = filename.split('?')[0].split('#')[0];
    const baseName = cleanName.split('/').pop().toLowerCase();
    if (aliases[baseName]) return aliases[baseName];
    const ext = baseName.includes('.') ? baseName.split('.').pop() : baseName;
    return aliases[ext] || ext;
}
